name: ugc-script-splitter
region: nyc

# Build configuration
builds:
  - build_command: npm run install-all && npm run build
    dockerfile_path: ""
    github:
      branch: main
      deploy_on_push: true
      repo: ""
    source_dir: /

# Run configuration
run_command: npm start

# Health check configuration
health_check:
  http_path: /api/health
  initial_timeout_seconds: 10
  period_seconds: 10
  timeout_seconds: 5
  success_threshold: 1
  failure_threshold: 3

# Environment variables (set these in DigitalOcean dashboard)
# Required:
#   OPENAI_API_KEY
#   NODE_ENV=production
# Optional:
#   GOOGLE_GEMINI_API_KEY
#   VERTEX_PROJECT_ID
#   VERTEX_LOCATION
#   GOOGLE_APPLICATION_CREDENTIALS
#   KIEAI_API_KEY

# Instance configuration
instance_size_slug: basic-xxs
instance_count: 1

# HTTP port (App Platform sets PORT automatically)
http_port: 8080

# Static site configuration (not used - we serve static files from Express)
# static_sites: []

